name: Lazarus Test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Lazarus
      run: |
        sudo apt-get update
        sudo apt-get install -y lazarus libqt5pas-dev libgl1-mesa-dev

    - name: lazopenglcontext
      run: |
        lazbuild --build-ide= --add-package lazopenglcontext

    - name: MangoHud deps
      run: |
          sudo apt update
          sudo apt install gcc-multilib g++-multilib ninja-build python3-setuptools python3-wheel mesa-common-dev libxnvctrl-dev libdbus-1-dev python3-numpy python3-matplotlib unzip
          sudo pip3 install 'meson>=0.60' mako
    - name: MangoHud
      run: |
          wget https://github.com/Franck-Nein/goverlay/releases/download/Ignore(Mangohud)/MangoHud-artifacts.zip
          unzip MangoHud-artifacts.zip -d MangoHud
          cd MangoHud
          ./build.sh install
          cd ..

    - name: Build GOverlay
      run: |
        make

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: goverlay-artifacts
        path: goverlay  # Change this path to the directory where your artifacts are generated
