name: Build GOverlay

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Lazarus
      run: |
        echo -e "\ndeb http://cz.archive.ubuntu.com/ubuntu jammy main universe" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt install lcl-2.2
        sudo apt-get install -y lazarus-2.2
        sudo apt-get install -y libqt5pas-dev
        sudo apt-get install -y mangohud
        lazbuild --build-ide= --add-package lazopenglcontext
        
    - name: Build GOverlay
      run: |
        make

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: goverlay-artifacts
        path: goverlay  # Change this path to the directory where your artifacts are generated
