name: Build GOverlay

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Lazarus
      run: |
        sudo apt-get update
        sudo apt-get install -y lazarus libqt5pas-dev mangohud libgl1-mesa-dev
        sudo lazbuild --build-ide= --add-package lazopenglcontext freetypelaz

    - name: c?
      run: |
        wget https://musl.libc.org/releases/musl-1.2.4.tar.gz
        tar -xzvf musl-1.2.4.tar.gz
        cd musl-1.2.4
        ./configure && make
        sudo make install
        cd ..
        
    - name: Build GOverlay
      run: |
        sudo make

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: goverlay-artifacts
        path: goverlay  # Change this path to the directory where your artifacts are generated
